In [2]:
import pandas
import numpy as np

In [3]:
array = np.array([[1,2,3],[2,3,4]])  #列表转化为矩阵
print(array)
print('number of dim:',array.ndim)  # 维度
print('shape :',array.shape)    # 行数和列数
print('size:',array.size)   # 元素个数

[[1 2 3]
 [2 3 4]]
number of dim: 2
shape : (2, 3)
size: 6


In [4]:
a = np.arange(10,30,1).reshape((4,5)) #4列5行
print(a)
b = np.linspace(1,10,20).reshape((5,4))#1~10分20線段 
print(b)

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 1.          1.47368421  1.94736842  2.42105263]
 [ 2.89473684  3.36842105  3.84210526  4.31578947]
 [ 4.78947368  5.26315789  5.73684211  6.21052632]
 [ 6.68421053  7.15789474  7.63157895  8.10526316]
 [ 8.57894737  9.05263158  9.52631579 10.        ]]


In [5]:
a = np.array([[1,0,2],[1,3,1]])
b = np.array([[3,1],[2,1],[1,0]])
c = np.arange(2,14)
print(c)
print(np.cumsum(c)) #項目累加
print(np.diff(a)) #前項差
print(b.dot(a)) # 矩陣b乘a
print(np.argmin(c))#最小的位置
print(np.argmax(c))#最大
print(np.sort(a)) #排序
print(np.nonzero(a))#不為0的位置
print(np.transpose(a))#行列互換
print(np.clip(a,1,2))#(a,<1為1,>2為2)
for item in c.flat:
    print(item)

[ 2  3  4  5  6  7  8  9 10 11 12 13]
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[-1  2]
 [ 2 -2]]
[[4 3 7]
 [3 3 5]
 [1 0 2]]
0
11
[[0 1 2]
 [1 1 3]]
(array([0, 0, 1, 1, 1]), array([0, 2, 0, 1, 2]))
[[1 1]
 [0 3]
 [2 1]]
[[1 1 2]
 [1 2 1]]
2
3
4
5
6
7
8
9
10
11
12
13


In [9]:
A = np.array([1,1,1])
B = np.array([2,2,2])
         
print(np.vstack((A,B)))# AB上下合併
print(np.hstack((A,B)))#AB左右合併



[[1 1 1]
 [2 2 2]]
[1 1 1 2 2 2]
